# 异常处理

## 异常的分类

* `Throwable`
  * `Error`
  * `Exception`
    * `<? extends Exception>` // checked exception
    * `<? extends RuntimeException>` // unchecked exception

> 异常处理不是面向对象的特性

## 异常处理的基本模型

### 终止模型

一旦异常被抛出，就表明错误已无法挽回，不能继续执行原来的逻辑

### 恢复模型

异常处理的工作是修正错误，然后尝试继续执行原来的逻辑

> 一般都使用终止模型，恢复模型会过于耦合

## 异常说明

异常说明用`throws`，后面跟着所有潜在的异常类型

> 编译时异常(`checked exception`)：要么进行处理，要么进行异常说明

## 捕获异常

* 监控区域`guarded region`

  一段可能产生异常的代码，并且后面跟着处理这些异常的代码

* `try-catch`语句和`finally`语句

```java
// 抛出异常后，会根据异常的类型从上往下寻找处理该异常类型的处理逻辑，类型匹配遵循多态性
try {
    // code that might generate exception
} catch (NullPointerException e) {
    // 处理NullPointerException 
} catch (Exception e) {
    // 处理所有异常，因为Exception是所有异常的父类
} finally {
    // 无论异常是否被抛出，finally语句块总会执行
}
```

## 自定义异常

```java
// simple checked exception
class SimpleException extends Exception {

}

// simple unchecked exception
class SimpleRuntimeException extends RuntimeException {

}

public class Test {
    // 抛出异常，让调用者处理
    static void throwSimpleException() throws SimpleException {
        throw new SimpleException();
    }

    static void fixSimpleException() {
        try {
            // 编译时异常必须处理
            throw new SimpleException();
        } catch (SimpleException e) {
            e.printStackTrace();
        }
    }

    static void throwSimpleRuntimeException() {
        // 运行时异常不必处理
        throw new SimpleRuntimeException();
    }
}
```

## 方法调用栈轨迹

栈顶：存储了调用序列中的最后一个方法调用(`Throwable`被创建和抛出的地方)

栈底：存储了调用序列中的第一个方法调用

* `printStackTrace()// 打印栈轨迹`
* `getStackTrace() // 访问栈轨迹`

## 异常链

在捕获一个异常后抛出另一个新异常，并把原来的异常信息保存下来，这样就形成了异常链

`Throwable`的构造函数中的`cause`参数用于传递异常信息，也可用`initCause()`

## 异常对继承的影响

子类方法只能抛出父类方法的异常说明列表中的异常或子类异常
